rain_map = {0.5: "Low Rainfall", 1.0: "Normal Rainfall", 1.2: "High Rainfall"}

config_ssd_maize = {
    "name": "eth_docker_test",
    "workDir": "/userdata/out/eth_docker/test",
    "templateDir": "templates/",
    "weatherDir": "weathers/",
    "threads": 2,
    "cores": 4,
    "exportRunlist": True,
    "ghr_root": "base/GHR/",
    "default_setup": {
        "include": ["userdata/MZCER047.CUL"],
        "template": "SSMZ8301.SNX",
        "sites": "xy_from_vector::shapes/fivearcmin_pt_ssd.shp",
        "startYear": 1983,
        "nyers": 37,
        "ingeno": "990006",
        "cname": "SC403",
        "icin": 10,
        "icsw%": 25,
        "flhst": "FH302",
        "fhdur": 10,
        "icren": 0.8,
        "erain": 1.0,
        "sdate": "1983-01-01",
        "pfrst": "1983-03-01",
        "plast": "1983-05-23",
        "id_soil": "lookup_ghr::raster::rasters/GHR_ssd.tif",
        "wsta": "lookup_wth::ETCP::vector::shapes/fivearcmin_pt_ssd.shp::ID",
        "ic_layers": "generate_ic_layers::$id_soil",
        "ramt": 0,
        "fen_tot": 100.0,
        "fertilizers": "split_fert_dap_percent::$fen_tot::5::0::50::30::50",
        "irrig": "N",
    },
    "dssat": {"executable": "/app/dssat47/dscsm047"},
    "analytics_setup": {"per_pixel_prefix": "pp", "singleOutput": "false"},
    "runs": [
        # {
        #     "season": "Main",
        #     "name": "maize_irrig",
        #     "harvestArea": "raster::rasters/spam2010v1r0_ssd_harvested-area_maiz_i.tif",
        #     "icsw%": 50,
        #     "flhst": "FH301",
        #     "icres": 200,
        #     "icrt": 20,
        #     "fen_tot": 100,
        #     "irrig": "A"
        # },
        {
            "season": "Main",
            "name": "maize_rf_highN",
            "harvestArea": "raster::rasters/spam2010v1r0_ssd_harvested-area_maiz_h.tif",
            "icres": 100,
            "icrt": 10,
            "fen_tot": 100,
            "icsw%": 25,
        },
        {
            "season": "Main",
            "name": "maize_rf_lowN",
            "harvestArea": "raster::rasters/spam2010v1r0_ssd_harvested-area_maiz_l.tif",
            "ramt": 500,
            "icres": 50,
            "icrt": 5,
            "fen_tot": 10,
            "icsw%": 25,
        },
        {
            "season": "Main",
            "name": "maize_rf_0N",
            "harvestArea": "raster::rasters/spam2010v1r0_ssd_harvested-area_maiz_s.tif",
            "ramt": 500,
            "icres": 0,
            "icrt": 0,
            "fen_tot": 0,
            "icsw%": 25,
        },
    ],
}

config_ssd_sorghum = {
    "name": "eth_docker_test",
    "workDir": "/userdata/out/eth_docker/test",
    "templateDir": "templates/",
    "weatherDir": "weathers/",
    "threads": 2,
    "cores": 4,
    "exportRunlist": True,
    "ghr_root": "base/GHR/",
    "default_setup": {
        "include": ["userdata/SGCER047.CUL"],
        "template": "SSSG8301.SNX",
        "sites": "xy_from_vector::shapes/fivearcmin_pt_ssd.shp",
        "startYear": 1983,
        "nyers": 37,
        "ingeno": "IB0059",
        "cname": "IS15401",
        "icin": 10,
        "icsw%": 25,
        "flhst": "FH302",
        "fhdur": 10,
        "icren": 0.8,
        "erain": 1.0,
        "sdate": "1983-01-01",
        "pfrst": "1983-03-01",
        "plast": "1983-05-23",
        "id_soil": "lookup_ghr::raster::rasters/GHR_ssd.tif",
        "wsta": "lookup_wth::ETCP::vector::shapes/fivearcmin_pt_ssd.shp::ID",
        "ic_layers": "generate_ic_layers::$id_soil",
        "ramt": 0,
        "fen_tot": 100.0,
        "fertilizers": "split_fert_dap_percent::$fen_tot::5::0::50::30::50",
        "irrig": "N",
    },
    "dssat": {"executable": "/app/dssat47/dscsm047"},
    "analytics_setup": {"per_pixel_prefix": "pp", "singleOutput": "false"},
    "runs": [
        {
            "season": "Main",
            "name": "sorghum_irrig",
            "harvestArea": "raster::rasters/spam2010v1r0_ssd_harvested-area_sorg_i.tif",
            "icsw%": 50,
            "flhst": "FH301",
            "icres": 200,
            "icrt": 20,
            "fen_tot": 100,
            "irrig": "A",
        },
        {
            "season": "Main",
            "name": "sorghum_rf_highN",
            "harvestArea": "raster::rasters/spam2010v1r0_ssd_harvested-area_sorg_h.tif",
            "icres": 100,
            "icrt": 10,
            "fen_tot": 100,
            "icsw%": 25,
        },
        {
            "season": "Main",
            "name": "sorghum_rf_lowN",
            "harvestArea": "raster::rasters/spam2010v1r0_ssd_harvested-area_sorg_l.tif",
            "ramt": 500,
            "icres": 50,
            "icrt": 5,
            "fen_tot": 10,
            "icsw%": 25,
        },
        {
            "season": "Main",
            "name": "sorghum_rf_0N",
            "harvestArea": "raster::rasters/spam2010v1r0_ssd_harvested-area_sorg_s.tif",
            "ramt": 500,
            "icres": 0,
            "icrt": 0,
            "fen_tot": 0,
            "icsw%": 25,
        },
    ],
}

config_eth_maize = {
    "name": "eth_docker_test",
    "workDir": "/userdata/out/eth_docker/test",
    "templateDir": "templates/",
    "weatherDir": "weathers/",
    "threads": 2,
    "cores": 4,
    "exportRunlist": True,
    "ghr_root": "base/GHR/",
    "default_setup": {
        "include": ["userdata/MZCER047.CUL"],
        "template": "ETMZ8301.SNX",
        "sites": "xy_from_vector::shapes/fivearcmin_pt_eth.shp",
        "startYear": 1983,
        "nyers": 37,
        "ingeno": "990011",
        "cname": "BH540",
        "icin": 10,
        "icsw%": 25,
        "flhst": "FH302",
        "fhdur": 10,
        "icren": 0.8,
        "erain": 1.0,
        "sdate": "1983-01-01",
        "pfrst": "1983-05-01",
        "plast": "1983-06-15",
        "id_soil": "lookup_ghr::raster::rasters/GHR_eth.tif",
        "wsta": "lookup_wth::ETCP::vector::shapes/fivearcmin_pt_eth.shp::ID",
        "ic_layers": "generate_ic_layers::$id_soil",
        "ramt": 0,
        "fen_tot": 100.0,
        "fertilizers": "split_fert_dap_percent::$fen_tot::5::0::50::30::50",
        "irrig": "N",
    },
    "dssat": {"executable": "/app/dssat47/dscsm047"},
    "analytics_setup": {"per_pixel_prefix": "pp", "singleOutput": "false"},
    "runs": [
        {
            "season": "Meher",
            "name": "maize_irrig",
            "harvestArea": "raster::rasters/spam2010v1r0_eth_harvested-area_maiz_i.tif",
            "icsw%": 50,
            "flhst": "FH301",
            "icres": 200,
            "icrt": 20,
            "fen_tot": 100,
            "irrig": "A",
        },
        {
            "season": "Meher",
            "name": "maize_rf_highN",
            "harvestArea": "raster::rasters/spam2010v1r0_eth_harvested-area_maiz_h.tif",
            "icres": 100,
            "icrt": 10,
            "fen_tot": 100,
            "icsw%": 25,
        },
        {
            "season": "Meher",
            "name": "maize_rf_lowN",
            "harvestArea": "raster::rasters/spam2010v1r0_eth_harvested-area_maiz_l.tif",
            "ramt": 500,
            "icres": 50,
            "icrt": 5,
            "fen_tot": 10,
            "icsw%": 25,
        },
        {
            "season": "Meher",
            "name": "maize_rf_0N",
            "harvestArea": "raster::rasters/spam2010v1r0_eth_harvested-area_maiz_s.tif",
            "ramt": 500,
            "icres": 0,
            "icrt": 0,
            "fen_tot": 0,
            "icsw%": 25,
        },
    ],
}

config_eth_sorghum = {
    "name": "eth_docker_test",
    "workDir": "/userdata/out/eth_docker/test",
    "templateDir": "templates/",
    "weatherDir": "weathers/",
    "threads": 2,
    "cores": 4,
    "exportRunlist": True,
    "ghr_root": "base/GHR/",
    "default_setup": {
        "include": ["userdata/SGCER047.CUL"],
        "template": "ETSG8301.SNX",
        "sites": "xy_from_vector::shapes/fivearcmin_pt_eth.shp",
        "startYear": 1983,
        "nyers": 37,
        "ingeno": "IB0061",
        "cname": "Teshale",
        "icin": 10,
        "icsw%": 25,
        "flhst": "FH302",
        "fhdur": 10,
        "icren": 0.8,
        "erain": 1.0,
        "sdate": "1983-01-01",
        "pfrst": "1983-05-01",
        "plast": "1983-06-15",
        "id_soil": "lookup_ghr::raster::rasters/GHR_eth.tif",
        "wsta": "lookup_wth::ETCP::vector::shapes/fivearcmin_pt_eth.shp::ID",
        "ic_layers": "generate_ic_layers::$id_soil",
        "ramt": 0,
        "fen_tot": 100.0,
        "fertilizers": "split_fert_dap_percent::$fen_tot::5::0::50::30::50",
        "irrig": "N",
    },
    "dssat": {"executable": "/app/dssat47/dscsm047"},
    "analytics_setup": {"per_pixel_prefix": "pp", "singleOutput": "false"},
    "runs": [
        {
            "season": "Meher",
            "name": "sorghum_irrig",
            "harvestArea": "raster::rasters/spam2010v1r0_eth_harvested-area_sorg_i.tif",
            "icsw%": 50,
            "flhst": "FH301",
            "icres": 200,
            "icrt": 20,
            "fen_tot": 100,
            "irrig": "A",
        },
        {
            "season": "Meher",
            "name": "sorghum_rf_highN",
            "harvestArea": "raster::rasters/spam2010v1r0_eth_harvested-area_sorg_h.tif",
            "icres": 100,
            "icrt": 10,
            "fen_tot": 100,
            "icsw%": 25,
        },
        {
            "season": "Meher",
            "name": "sorghum_rf_lowN",
            "harvestArea": "raster::rasters/spam2010v1r0_eth_harvested-area_sorg_l.tif",
            "ramt": 500,
            "icres": 50,
            "icrt": 5,
            "fen_tot": 10,
            "icsw%": 25,
        },
        {
            "season": "Meher",
            "name": "sorghum_rf_0N",
            "harvestArea": "raster::rasters/spam2010v1r0_eth_harvested-area_sorg_s.tif",
            "ramt": 500,
            "icres": 0,
            "icrt": 0,
            "fen_tot": 0,
            "icsw%": 25,
        },
    ],
}

config_ken_maize = {
    "name": "eth_docker_test",
    "workDir": "/userdata/out/eth_docker/test",
    "templateDir": "templates/",
    "weatherDir": "weathers/",
    "threads": 2,
    "cores": 4,
    "exportRunlist": True,
    "ghr_root": "base/GHR/",
    "default_setup": {
        "include": ["userdata/MZCER047.CUL"],
        "template": "KEMZ8301.SNX",
        "sites": "xy_from_vector::shapes/fivearcmin_pt_ken.shp",
        "startYear": 1983,
        "nyers": 37,
        "ingeno": "KY0005",
        "cname": "H625",
        "icin": 10,
        "icsw%": 25,
        "flhst": "FH302",
        "fhdur": 10,
        "icren": 0.8,
        "erain": 1.0,
        "sdate": "1983-01-01",
        "pfrst": "1983-03-15",
        "plast": "1983-05-30",
        "id_soil": "lookup_ghr::raster::rasters/GHR_ken.tif",
        "wsta": "lookup_wth::ETCP::vector::shapes/fivearcmin_pt_ken.shp::ID",
        "ic_layers": "generate_ic_layers::$id_soil",
        "ramt": 0,
        "fen_tot": 100.0,
        "fertilizers": "split_fert_dap_percent::$fen_tot::5::0::50::30::50",
        "irrig": "N",
    },
    "dssat": {"executable": "/app/dssat47/dscsm047"},
    "analytics_setup": {"per_pixel_prefix": "pp", "singleOutput": "false"},
    "runs": [
        {
            "season": "Long rains",
            "name": "maize_irrig",
            "harvestArea": "raster::rasters/spam2010v1r0_ken_harvested-area_maiz_i.tif",
            "icsw%": 50,
            "flhst": "FH301",
            "icres": 200,
            "icrt": 20,
            "fen_tot": 100,
            "irrig": "A",
        },
        {
            "season": "Long rains",
            "name": "maize_rf_highN",
            "harvestArea": "raster::rasters/spam2010v1r0_ken_harvested-area_maiz_h.tif",
            "icres": 100,
            "icrt": 10,
            "fen_tot": 100,
            "icsw%": 25,
        },
        {
            "season": "Long rains",
            "name": "maize_rf_lowN",
            "harvestArea": "raster::rasters/spam2010v1r0_ken_harvested-area_maiz_l.tif",
            "ramt": 500,
            "icres": 50,
            "icrt": 5,
            "fen_tot": 10,
            "icsw%": 25,
        },
        {
            "season": "Long rains",
            "name": "maize_rf_0N",
            "harvestArea": "raster::rasters/spam2010v1r0_ken_harvested-area_maiz_s.tif",
            "ramt": 500,
            "icres": 0,
            "icrt": 0,
            "fen_tot": 0,
            "icsw%": 25,
        },
    ],
}

config_ken_sorghum = {
    "name": "eth_docker_test",
    "workDir": "/userdata/out/eth_docker/test",
    "templateDir": "templates/",
    "weatherDir": "weathers/",
    "threads": 2,
    "cores": 4,
    "exportRunlist": True,
    "ghr_root": "base/GHR/",
    "default_setup": {
        "include": ["userdata/SGCER047.CUL"],
        "template": "KESG8301.SNX",
        "sites": "xy_from_vector::shapes/fivearcmin_pt_ken.shp",
        "startYear": 1983,
        "nyers": 37,
        "ingeno": "IB0046",
        "cname": "M-35-1",
        "icin": 10,
        "icsw%": 25,
        "flhst": "FH302",
        "fhdur": 10,
        "icren": 0.8,
        "erain": 1.0,
        "sdate": "1983-01-01",
        "pfrst": "1983-04-01",
        "plast": "1983-05-30",
        "id_soil": "lookup_ghr::raster::rasters/GHR_ken.tif",
        "wsta": "lookup_wth::ETCP::vector::shapes/fivearcmin_pt_ken.shp::ID",
        "ic_layers": "generate_ic_layers::$id_soil",
        "ramt": 0,
        "fen_tot": 100.0,
        "fertilizers": "split_fert_dap_percent::$fen_tot::5::0::50::30::50",
        "irrig": "N",
    },
    "dssat": {"executable": "/app/dssat47/dscsm047"},
    "analytics_setup": {"per_pixel_prefix": "pp", "singleOutput": "false"},
    "runs": [
        {
            "name": "sorghum_irrig",
            "harvestArea": "raster::rasters/spam2010v1r0_ken_harvested-area_sorg_i.tif",
            "icsw%": 50,
            "flhst": "FH301",
            "icres": 200,
            "icrt": 20,
            "fen_tot": 100,
            "irrig": "A",
        },
        {
            "name": "sorghum_rf_highN",
            "harvestArea": "raster::rasters/spam2010v1r0_ken_harvested-area_sorg_h.tif",
            "icres": 100,
            "icrt": 10,
            "fen_tot": 100,
            "icsw%": 25,
        },
        {
            "name": "sorghum_rf_lowN",
            "harvestArea": "raster::rasters/spam2010v1r0_ken_harvested-area_sorg_l.tif",
            "ramt": 500,
            "icres": 50,
            "icrt": 5,
            "fen_tot": 10,
            "fen_tot": 10,
            "icsw%": 25,
        },
        {
            "name": "sorghum_rf_0N",
            "harvestArea": "raster::rasters/spam2010v1r0_ken_harvested-area_sorg_s.tif",
            "ramt": 500,
            "icres": 0,
            "icrt": 0,
            "fen_tot": 0,
            "icsw%": 25,
            "icrt": 0,
        },
    ],
}

config_uga_maize = {
    "name": "eth_docker_test",
    "workDir": "/userdata/out/eth_docker/test",
    "templateDir": "templates/",
    "weatherDir": "weathers/",
    "threads": 2,
    "cores": 4,
    "exportRunlist": True,
    "ghr_root": "base/GHR/",
    "default_setup": {
        "include": ["userdata/MZCER047.CUL"],
        "template": "UGMZ8301.SNX",
        "sites": "xy_from_vector::shapes/fivearcmin_pt_uga.shp",
        "startYear": 1983,
        "nyers": 37,
        "ingeno": "990018",
        "cname": "Longe-5",
        "icin": 10,
        "icsw%": 25,
        "flhst": "FH302",
        "fhdur": 10,
        "icren": 0.8,
        "erain": 1.0,
        "sdate": "1983-01-01",
        "pfrst": "1983-03-01",
        "plast": "1983-05-20",
        "id_soil": "lookup_ghr::raster::rasters/GHR_uga.tif",
        "wsta": "lookup_wth::ETCP::vector::shapes/fivearcmin_pt_uga.shp::ID",
        "ic_layers": "generate_ic_layers::$id_soil",
        "ramt": 0,
        "fen_tot": 100.0,
        "fertilizers": "split_fert_dap_percent::$fen_tot::5::0::50::30::50",
        "irrig": "N",
    },
    "dssat": {"executable": "/app/dssat47/dscsm047"},
    "analytics_setup": {"per_pixel_prefix": "pp", "singleOutput": "false"},
    "runs": [
        {
            "season": "Long rains",
            "name": "maize_irrig",
            "harvestArea": "raster::rasters/spam2010v1r0_uga_harvested-area_maiz_i.tif",
            "icsw%": 50,
            "flhst": "FH301",
            "icres": 200,
            "icrt": 20,
            "fen_tot": 100,
            "irrig": "A",
        },
        {
            "season": "Long rains",
            "name": "maize_rf_highN",
            "harvestArea": "raster::rasters/spam2010v1r0_uga_harvested-area_maiz_h.tif",
            "icres": 100,
            "icrt": 10,
            "fen_tot": 100,
            "icsw%": 25,
        },
        {
            "season": "Long rains",
            "name": "maize_rf_lowN",
            "harvestArea": "raster::rasters/spam2010v1r0_uga_harvested-area_maiz_l.tif",
            "ramt": 500,
            "icres": 50,
            "icrt": 5,
            "fen_tot": 10,
            "icsw%": 25,
        },
        {
            "season": "Long rains",
            "name": "maize_rf_0N",
            "harvestArea": "raster::rasters/spam2010v1r0_uga_harvested-area_maiz_s.tif",
            "ramt": 500,
            "icres": 0,
            "icrt": 0,
            "fen_tot": 0,
            "icsw%": 25,
        },
    ],
}

config_uga_sorghum = {
    "name": "eth_docker_test",
    "workDir": "/userdata/out/eth_docker/test",
    "templateDir": "templates/",
    "weatherDir": "weathers/",
    "threads": 2,
    "cores": 4,
    "exportRunlist": True,
    "ghr_root": "base/GHR/",
    "default_setup": {
        "include": ["userdata/SGCER047.CUL"],
        "template": "UGSG8301.SNX",
        "sites": "xy_from_vector::shapes/fivearcmin_pt_uga.shp",
        "startYear": 1983,
        "nyers": 37,
        "ingeno": "IB0051",
        "cname": "CARGIL_1090",
        "icin": 10,
        "icsw%": 25,
        "flhst": "FH302",
        "fhdur": 10,
        "icren": 0.8,
        "erain": 1.0,
        "sdate": "1983-01-01",
        "pfrst": "1983-03-01",
        "plast": "1983-05-20",
        "id_soil": "lookup_ghr::raster::rasters/GHR_uga.tif",
        "wsta": "lookup_wth::ETCP::vector::shapes/fivearcmin_pt_uga.shp::ID",
        "ic_layers": "generate_ic_layers::$id_soil",
        "ramt": 0,
        "fen_tot": 100.0,
        "fertilizers": "split_fert_dap_percent::$fen_tot::5::0::50::30::50",
        "irrig": "N",
    },
    "dssat": {"executable": "/app/dssat47/dscsm047"},
    "analytics_setup": {"per_pixel_prefix": "pp", "singleOutput": "false"},
    "runs": [
        # {
        #     "season": "Long rains",
        #     "name": "sorghum_irrig",
        #     "harvestArea": "raster::rasters/spam2010v1r0_uga_harvested-area_sorg_i.tif",
        #     "icsw%": 50,
        #     "flhst": "FH301",
        #     "icres": 200,
        #     "icrt": 20,
        #     "fen_tot": 100,
        #     "irrig": "A"
        # },
        {
            "season": "Long rains",
            "name": "sorghum_rf_highN",
            "harvestArea": "raster::rasters/spam2010v1r0_uga_harvested-area_sorg_h.tif",
            "icres": 100,
            "icrt": 10,
            "fen_tot": 100,
            "icsw%": 25,
        },
        {
            "season": "Long rains",
            "name": "sorghum_rf_lowN",
            "harvestArea": "raster::rasters/spam2010v1r0_uga_harvested-area_sorg_l.tif",
            "ramt": 500,
            "icres": 50,
            "icrt": 5,
            "fen_tot": 10,
            "icsw%": 25,
        },
        {
            "season": "Long rains",
            "name": "sorghum_rf_0N",
            "harvestArea": "raster::rasters/spam2010v1r0_uga_harvested-area_sorg_s.tif",
            "ramt": 500,
            "icres": 0,
            "icrt": 0,
            "fen_tot": 0,
            "icsw%": 25,
        },
    ],
}

config_som_maize = {
    "name": "eth_docker_test",
    "workDir": "/userdata/out/eth_docker/test",
    "templateDir": "templates/",
    "weatherDir": "weathers/",
    "threads": 2,
    "cores": 4,
    "exportRunlist": True,
    "ghr_root": "base/GHR/",
    "default_setup": {
        "include": ["userdata/MZCER047.CUL"],
        "template": "SOMZ8301.SNX",
        "sites": "xy_from_vector::shapes/fivearcmin_pt_som.shp",
        "startYear": 1983,
        "nyers": 37,
        "ingeno": "990006",
        "cname": "SC403",
        "icin": 10,
        "icsw%": 25,
        "flhst": "FH302",
        "fhdur": 10,
        "icren": 0.8,
        "erain": 1.0,
        "sdate": "1983-01-01",
        "pfrst": "1983-04-20",
        "plast": "1983-05-10",
        "id_soil": "lookup_ghr::raster::rasters/GHR_som.tif",
        "wsta": "lookup_wth::ETCP::vector::shapes/fivearcmin_pt_som.shp::ID",
        "ic_layers": "generate_ic_layers::$id_soil",
        "ramt": 0,
        "fen_tot": 100.0,
        "fertilizers": "split_fert_dap_percent::$fen_tot::5::0::50::30::50",
        "irrig": "N",
    },
    "dssat": {"executable": "/app/dssat47/dscsm047"},
    "analytics_setup": {"per_pixel_prefix": "pp", "singleOutput": "false"},
    "runs": [
        {
            "season": "Gu - main rains",
            "name": "maize_irrig",
            "harvestArea": "raster::rasters/spam2010v1r0_som_harvested-area_maiz_i.tif",
            "icsw%": 50,
            "flhst": "FH301",
            "icres": 200,
            "icrt": 20,
            "fen_tot": 100,
            "irrig": "A",
        },
        {
            "season": "Gu - main rains",
            "name": "maize_rf_highN",
            "harvestArea": "raster::rasters/spam2010v1r0_som_harvested-area_maiz_h.tif",
            "icres": 100,
            "icrt": 10,
            "fen_tot": 100,
            "icsw%": 25,
        },
        {
            "season": "Gu - main rains",
            "name": "maize_rf_lowN",
            "harvestArea": "raster::rasters/spam2010v1r0_som_harvested-area_maiz_l.tif",
            "ramt": 500,
            "icres": 50,
            "icrt": 5,
            "fen_tot": 10,
            "icsw%": 25,
        },
        {
            "season": "Gu - main rains",
            "name": "maize_rf_0N",
            "harvestArea": "raster::rasters/spam2010v1r0_som_harvested-area_maiz_s.tif",
            "ramt": 500,
            "icres": 0,
            "icrt": 0,
            "fen_tot": 0,
            "icsw%": 25,
        },
    ],
}

config_som_sorghum = {
    "name": "eth_docker_test",
    "workDir": "/userdata/out/eth_docker/test",
    "templateDir": "templates/",
    "weatherDir": "weathers/",
    "threads": 2,
    "cores": 4,
    "exportRunlist": True,
    "ghr_root": "base/GHR/",
    "default_setup": {
        "include": ["userdata/SGCER047.CUL"],
        "template": "SOSG8301.SNX",
        "sites": "xy_from_vector::shapes/fivearcmin_pt_som.shp",
        "startYear": 1983,
        "nyers": 37,
        "ingeno": "IB0046",
        "cname": "M-35-1",
        "icin": 10,
        "icsw%": 25,
        "flhst": "FH302",
        "fhdur": 10,
        "icren": 0.8,
        "erain": 1.0,
        "sdate": "1983-01-01",
        "pfrst": "1983-04-20",
        "plast": "1983-05-10",
        "id_soil": "lookup_ghr::raster::rasters/GHR_som.tif",
        "wsta": "lookup_wth::ETCP::vector::shapes/fivearcmin_pt_som.shp::ID",
        "ic_layers": "generate_ic_layers::$id_soil",
        "ramt": 0,
        "fen_tot": 100.0,
        "fertilizers": "split_fert_dap_percent::$fen_tot::2::0::50::30::50",
        "irrig": "N",
    },
    "dssat": {"executable": "/app/dssat47/dscsm047"},
    "analytics_setup": {"per_pixel_prefix": "pp", "singleOutput": "false"},
    "runs": [
        {
            "season": "Gu - main rains",
            "name": "sorghum_irrig",
            "harvestArea": "raster::rasters/spam2010v1r0_som_harvested-area_sorg_i.tif",
            "icsw%": 50,
            "flhst": "FH301",
            "icres": 200,
            "icrt": 20,
            "fen_tot": 100,
            "irrig": "A",
        },
        {
            "season": "Gu - main rains",
            "name": "sorghum_rf_highN",
            "harvestArea": "raster::rasters/spam2010v1r0_som_harvested-area_sorg_h.tif",
            "icres": 100,
            "icrt": 10,
            "fen_tot": 100,
            "icsw%": 25,
        },
        {
            "season": "Gu - main rains",
            "name": "sorghum_rf_lowN",
            "harvestArea": "raster::rasters/spam2010v1r0_som_harvested-area_sorg_l.tif",
            "ramt": 500,
            "icres": 50,
            "icrt": 5,
            "fen_tot": 10,
            "icsw%": 25,
        },
        {
            "season": "Gu - main rains",
            "name": "sorghum_rf_0N",
            "harvestArea": "raster::rasters/spam2010v1r0_som_harvested-area_sorg_s.tif",
            "ramt": 500,
            "icres": 0,
            "icrt": 0,
            "fen_tot": 0,
            "icsw%": 25,
        },
    ],
}

config_dji_maize = {
    "name": "eth_docker_test",
    "workDir": "/userdata/out/eth_docker/test",
    "templateDir": "templates/",
    "weatherDir": "weathers/",
    "threads": 2,
    "cores": 4,
    "exportRunlist": True,
    "ghr_root": "base/GHR/",
    "default_setup": {
        "include": ["userdata/MZCER047.CUL"],
        "template": "DJMZ8301.SNX",
        "sites": "xy_from_vector::shapes/fivearcmin_pt_dji.shp",
        "startYear": 1983,
        "nyers": 37,
        "ingeno": "990003",
        "cname": "SHORT SEASON",
        "icin": 10,
        "icsw%": 25,
        "flhst": "FH302",
        "fhdur": 10,
        "icren": 0.8,
        "erain": 1.0,
        "sdate": "1983-01-01",
        "pfrst": "1983-08-20",
        "plast": "1983-09-30",
        "id_soil": "lookup_ghr::raster::rasters/GHR_dji.tif",
        "wsta": "lookup_wth::ETCP::vector::shapes/fivearcmin_pt_dji.shp::ID",
        "ic_layers": "generate_ic_layers::$id_soil",
        "ramt": 0,
        "fen_tot": 100.0,
        "fertilizers": "split_fert_dap_percent::$fen_tot::5::0::50::30::50",
        "irrig": "N",
    },
    "dssat": {"executable": "/app/dssat47/dscsm047"},
    "analytics_setup": {"per_pixel_prefix": "pp", "singleOutput": "false"},
    "runs": [
        {
            "name": "maize_irrig",
            "harvestArea": "raster::rasters/spam2010v1r0_dji_harvested-area_maiz_i.tif",
            "icsw%": 50,
            "flhst": "FH301",
            "icres": 200,
            "icrt": 20,
            "fen_tot": 100,
            "irrig": "A",
        },
        # {
        #     "name": "maize_rf_highN",
        #     "harvestArea": "raster::rasters/spam2010v1r0_dji_harvested-area_maiz_h.tif",
        #     "icres": 100,
        #     "icrt": 10,
        #     "fen_tot": 100,
        #     "icsw%": 25,
        # },
        {
            "name": "maize_rf_lowN",
            "harvestArea": "raster::rasters/spam2010v1r0_dji_harvested-area_maiz_l.tif",
            "ramt": 500,
            "icres": 50,
            "icrt": 5,
            "fen_tot": 10,
            "icsw%": 25,
        },
        {
            "name": "maize_rf_0N",
            "harvestArea": "raster::rasters/spam2010v1r0_dji_harvested-area_maiz_s.tif",
            "ramt": 500,
            "icres": 0,
            "icrt": 0,
            "fen_tot": 0,
            "icsw%": 25,
        },
    ],
}

config_dji_sorghum = {
    "name": "eth_docker_test",
    "workDir": "/userdata/out/eth_docker/test",
    "templateDir": "templates/",
    "weatherDir": "weathers/",
    "threads": 2,
    "cores": 4,
    "exportRunlist": True,
    "ghr_root": "base/GHR/",
    "default_setup": {
        "include": ["userdata/SGCER047.CUL"],
        "template": "DJSG8301.SNX",
        "sites": "xy_from_vector::shapes/fivearcmin_pt_dji.shp",
        "startYear": 1983,
        "nyers": 37,
        "ingeno": "IB0048",
        "cname": "CSH-5",
        "icin": 10,
        "icsw%": 25,
        "flhst": "FH302",
        "fhdur": 10,
        "icren": 0.8,
        "erain": 1.0,
        "sdate": "1983-01-01",
        "pfrst": "1983-08-20",
        "plast": "1983-09-30",
        "id_soil": "lookup_ghr::raster::rasters/GHR_dji.tif",
        "wsta": "lookup_wth::ETCP::vector::shapes/fivearcmin_pt_dji.shp::ID",
        "ic_layers": "generate_ic_layers::$id_soil",
        "ramt": 0,
        "fen_tot": 100.0,
        "fertilizers": "split_fert_dap_percent::$fen_tot::5::0::50::30::50",
        "irrig": "N",
    },
    "dssat": {"executable": "/app/dssat47/dscsm047"},
    "analytics_setup": {"per_pixel_prefix": "pp", "singleOutput": "false"},
    "runs": [
        {
            "name": "sorghum_irrig",
            "harvestArea": "raster::rasters/spam2010v1r0_dji_harvested-area_sorg_i.tif",
            "icsw%": 50,
            "flhst": "FH301",
            "icres": 200,
            "icrt": 20,
            "fen_tot": 100,
            "irrig": "A",
        },
        # {
        #     "name": "sorghum_rf_highN",
        #     "harvestArea": "raster::rasters/spam2010v1r0_dji_harvested-area_sorg_h.tif",
        #     "icres": 100,
        #     "icrt": 10,
        #     "fen_tot": 100,
        #     "icsw%": 25,
        # },
        # {
        #     "name": "sorghum_rf_lowN",
        #     "harvestArea": "raster::rasters/spam2010v1r0_dji_harvested-area_sorg_l.tif",
        #     "ramt": 500,
        #     "icres": 50,
        #     "icrt": 5,
        #     "fen_tot": 10,
        #     "icsw%": 25,
        # },
        # {
        #     "name": "sorghum_rf_0N",
        #     "harvestArea": "raster::rasters/spam2010v1r0_dji_harvested-area_sorg_s.tif",
        #     "ramt": 500,
        #     "icres": 0,
        #     "icrt": 0,
        #     "fen_tot": 0,
        #     "icsw%": 25,
        # },
    ],
}

config_eri_maize = {
    "name": "eth_docker_test",
    "workDir": "/userdata/out/eth_docker/test",
    "templateDir": "templates/",
    "weatherDir": "weathers/",
    "threads": 2,
    "cores": 4,
    "exportRunlist": True,
    "ghr_root": "base/GHR/",
    "default_setup": {
        "include": ["userdata/MZCER047.CUL"],
        "template": "ERMZ8301.SNX",
        "sites": "xy_from_vector::shapes/fivearcmin_pt_eri.shp",
        "startYear": 1983,
        "nyers": 37,
        "ingeno": "990011",
        "cname": "BH540",
        "icin": 10,
        "icsw%": 25,
        "flhst": "FH302",
        "fhdur": 10,
        "icren": 0.8,
        "erain": 1.0,
        "sdate": "1983-01-01",
        "pfrst": "1983-06-01",
        "plast": "1983-07-31",
        "id_soil": "lookup_ghr::raster::rasters/GHR_eri.tif",
        "wsta": "lookup_wth::ETCP::vector::shapes/fivearcmin_pt_eri.shp::ID",
        "ic_layers": "generate_ic_layers::$id_soil",
        "ramt": 0,
        "fen_tot": 100.0,
        "fertilizers": "split_fert_dap_percent::$fen_tot::5::0::50::30::50",
        "irrig": "N",
    },
    "dssat": {"executable": "/app/dssat47/dscsm047"},
    "analytics_setup": {"per_pixel_prefix": "pp", "singleOutput": "false"},
    "runs": [
        {
            "season": "Kiremti - main rains",
            "name": "maize_irrig",
            "harvestArea": "raster::rasters/spam2010v1r0_eri_harvested-area_maiz_i.tif",
            "icsw%": 50,
            "flhst": "FH301",
            "icres": 200,
            "icrt": 20,
            "fen_tot": 100,
            "irrig": "A",
        },
        {
            "season": "Kiremti - main rains",
            "name": "maize_rf_highN",
            "harvestArea": "raster::rasters/spam2010v1r0_eri_harvested-area_maiz_h.tif",
            "icres": 100,
            "icrt": 10,
            "fen_tot": 100,
            "icsw%": 25,
        },
        {
            "season": "Kiremti - main rains",
            "name": "maize_rf_lowN",
            "harvestArea": "raster::rasters/spam2010v1r0_eri_harvested-area_maiz_l.tif",
            "ramt": 500,
            "icres": 50,
            "icrt": 5,
            "fen_tot": 10,
            "icsw%": 25,
        },
        {
            "season": "Kiremti - main rains",
            "name": "maize_rf_0N",
            "harvestArea": "raster::rasters/spam2010v1r0_eri_harvested-area_maiz_s.tif",
            "ramt": 500,
            "icres": 0,
            "icrt": 0,
            "fen_tot": 0,
            "icsw%": 25,
        },
    ],
}

config_eri_sorghum = {
    "name": "eth_docker_test",
    "workDir": "/userdata/out/eth_docker/test",
    "templateDir": "templates/",
    "weatherDir": "weathers/",
    "threads": 2,
    "cores": 4,
    "exportRunlist": True,
    "ghr_root": "base/GHR/",
    "default_setup": {
        "include": ["userdata/SGCER047.CUL"],
        "template": "ERSG8301.SNX",
        "sites": "xy_from_vector::shapes/fivearcmin_pt_eri.shp",
        "startYear": 1983,
        "nyers": 37,
        "ingeno": "IB0043",
        "cname": "CSH-6",
        "icin": 10,
        "icsw%": 25,
        "flhst": "FH302",
        "fhdur": 10,
        "icren": 0.8,
        "erain": 1.0,
        "sdate": "1983-01-01",
        "pfrst": "1983-06-01",
        "plast": "1983-07-31",
        "id_soil": "lookup_ghr::raster::rasters/GHR_eri.tif",
        "wsta": "lookup_wth::ETCP::vector::shapes/fivearcmin_pt_eri.shp::ID",
        "ic_layers": "generate_ic_layers::$id_soil",
        "ramt": 0,
        "fen_tot": 100.0,
        "fertilizers": "split_fert_dap_percent::$fen_tot::5::0::50::30::50",
        "irrig": "N",
    },
    "dssat": {"executable": "/app/dssat47/dscsm047"},
    "analytics_setup": {"per_pixel_prefix": "pp", "singleOutput": "false"},
    "runs": [
        {
            "season": "Kiremti - main rains",
            "name": "sorghum_irrig",
            "harvestArea": "raster::rasters/spam2010v1r0_eri_harvested-area_sorg_i.tif",
            "icsw%": 50,
            "flhst": "FH301",
            "icres": 200,
            "icrt": 20,
            "fen_tot": 100,
            "irrig": "A",
        },
        {
            "season": "Kiremti - main rains",
            "name": "sorghum_rf_highN",
            "harvestArea": "raster::rasters/spam2010v1r0_eri_harvested-area_sorg_h.tif",
            "icres": 100,
            "icrt": 10,
            "fen_tot": 100,
            "icsw%": 25,
        },
        {
            "season": "Kiremti - main rains",
            "name": "sorghum_rf_lowN",
            "harvestArea": "raster::rasters/spam2010v1r0_eri_harvested-area_sorg_l.tif",
            "ramt": 500,
            "icres": 50,
            "icrt": 5,
            "fen_tot": 10,
            "icsw%": 25,
        },
        {
            "season": "Kiremti - main rains",
            "name": "sorghum_rf_0N",
            "harvestArea": "raster::rasters/spam2010v1r0_eri_harvested-area_sorg_s.tif",
            "ramt": 500,
            "icres": 0,
            "icrt": 0,
            "fen_tot": 0,
            "icsw%": 25,
        },
    ],
}

config_sdn_maize = {
    "name": "eth_docker_test",
    "workDir": "/userdata/out/eth_docker/test",
    "templateDir": "templates/",
    "weatherDir": "weathers/",
    "threads": 2,
    "cores": 4,
    "exportRunlist": True,
    "ghr_root": "base/GHR/",
    "default_setup": {
        "include": ["userdata/MZCER047.CUL"],
        "template": "SDMZ8301.SNX",
        "sites": "xy_from_vector::shapes/fivearcmin_pt_sdn.shp",
        "startYear": 1983,
        "nyers": 37,
        "ingeno": "990002",
        "cname": "MEDIUM SEASON",
        "icin": 10,
        "icsw%": 25,
        "flhst": "FH302",
        "fhdur": 10,
        "icren": 0.8,
        "erain": 1.0,
        "sdate": "1983-01-01",
        "pfrst": "1983-07-01",
        "plast": "1983-08-15",
        "id_soil": "lookup_ghr::raster::rasters/GHR_sdn.tif",
        "wsta": "lookup_wth::ETCP::vector::shapes/fivearcmin_pt_sdn.shp::ID",
        "ic_layers": "generate_ic_layers::$id_soil",
        "ramt": 0,
        "fen_tot": 100.0,
        "fertilizers": "split_fert_dap_percent::$fen_tot::5::0::50::30::50",
        "irrig": "N",
    },
    "dssat": {"executable": "/app/dssat47/dscsm047"},
    "analytics_setup": {"per_pixel_prefix": "pp", "singleOutput": "false"},
    "runs": [
        # {
        #     "season": "Main rains",
        #     "name": "maize_irrig",
        #     "harvestArea": "raster::rasters/spam2010v1r0_sdn_harvested-area_maiz_i.tif",
        #     "icsw%": 50,
        #     "flhst": "FH301",
        #     "icres": 200,
        #     "icrt": 20,
        #     "fen_tot": 100,
        #     "irrig": "A"
        # },
        {
            "season": "Main rains",
            "name": "maize_rf_highN",
            "harvestArea": "raster::rasters/spam2010v1r0_sdn_harvested-area_maiz_h.tif",
            "icres": 100,
            "icrt": 10,
            "fen_tot": 100,
            "icsw%": 25,
        },
        {
            "season": "Main rains",
            "name": "maize_rf_lowN",
            "harvestArea": "raster::rasters/spam2010v1r0_sdn_harvested-area_maiz_l.tif",
            "ramt": 500,
            "icres": 50,
            "icrt": 5,
            "fen_tot": 10,
            "icsw%": 25,
        },
        {
            "season": "Main rains",
            "name": "maize_rf_0N",
            "harvestArea": "raster::rasters/spam2010v1r0_sdn_harvested-area_maiz_s.tif",
            "ramt": 500,
            "icres": 0,
            "icrt": 0,
            "fen_tot": 0,
            "icsw%": 25,
        },
    ],
}

config_sdn_sorghum = {
    "name": "eth_docker_test",
    "workDir": "/userdata/out/eth_docker/test",
    "templateDir": "templates/",
    "weatherDir": "weathers/",
    "threads": 2,
    "cores": 4,
    "exportRunlist": True,
    "ghr_root": "base/GHR/",
    "default_setup": {
        "include": ["userdata/SGCER047.CUL"],
        "template": "SDSG8301.SNX",
        "sites": "xy_from_vector::shapes/fivearcmin_pt_sdn.shp",
        "startYear": 1983,
        "nyers": 37,
        "ingeno": "IB0055",
        "cname": "PIONEER 850",
        "icin": 10,
        "icsw%": 25,
        "flhst": "FH302",
        "fhdur": 10,
        "icren": 0.8,
        "erain": 1.0,
        "sdate": "1983-01-01",
        "pfrst": "1983-07-01",
        "plast": "1983-08-15",
        "id_soil": "lookup_ghr::raster::rasters/GHR_sdn.tif",
        "wsta": "lookup_wth::ETCP::vector::shapes/fivearcmin_pt_sdn.shp::ID",
        "ic_layers": "generate_ic_layers::$id_soil",
        "ramt": 0,
        "fen_tot": 100.0,
        "fertilizers": "split_fert_dap_percent::$fen_tot::5::0::50::30::50",
        "irrig": "N",
    },
    "dssat": {"executable": "/app/dssat47/dscsm047"},
    "analytics_setup": {"per_pixel_prefix": "pp", "singleOutput": "false"},
    "runs": [
        {
            "season": "Main rains",
            "name": "sorghum_irrig",
            "harvestArea": "raster::rasters/spam2010v1r0_sdn_harvested-area_sorg_i.tif",
            "icsw%": 50,
            "flhst": "FH301",
            "icres": 200,
            "icrt": 20,
            "fen_tot": 100,
            "irrig": "A",
        },
        {
            "season": "Main rains",
            "name": "sorghum_rf_highN",
            "harvestArea": "raster::rasters/spam2010v1r0_sdn_harvested-area_sorg_h.tif",
            "icres": 100,
            "icrt": 10,
            "icsw%": 25,
        },
        {
            "season": "Main rains",
            "name": "sorghum_rf_lowN",
            "harvestArea": "raster::rasters/spam2010v1r0_sdn_harvested-area_sorg_l.tif",
            "ramt": 500,
            "icres": 50,
            "icrt": 5,
            "fen_tot": 10,
            "icsw%": 25,
        },
        {
            "season": "Main rains",
            "name": "sorghum_rf_0N",
            "harvestArea": "raster::rasters/spam2010v1r0_sdn_harvested-area_sorg_s.tif",
            "ramt": 500,
            "icres": 0,
            "icrt": 0,
            "fen_tot": 0,
            "icsw%": 25,
        },
    ],
}

crop_config = {
    "maize": {
        "South Sudan": config_ssd_maize,
        "Ethiopia": config_eth_maize,
        "Kenya": config_ken_maize,
        "Uganda": config_uga_maize,
        "Somalia": config_som_maize,
        "Djibouti": config_dji_maize,
        "Eritrea": config_eri_maize,
        "Sudan": config_sdn_maize,
    },
    "sorghum": {
        "South Sudan": config_ssd_sorghum,
        "Ethiopia": config_eth_sorghum,
        "Kenya": config_ken_sorghum,
        "Uganda": config_uga_sorghum,
        "Somalia": config_som_sorghum,
        "Djibouti": config_dji_sorghum,
        "Eritrea": config_eri_sorghum,
        "Sudan": config_sdn_sorghum,
    },
}
