commodity_type_map = {
    "Maize Flour": "bagged grain",
    "Relief Items": "break bulk",
    "Wood": "break bulk",
    "Metal bars": "break bulk",
    "22 Camels": "break bulk",
    "food, survival kits": "break bulk",
    "20 FT Container/Any common cargo": "containers",
    "Carton": "break bulk",
    "Crane": "break bulk",
    "100 sheep": "break bulk",
    "Domestic products": "break bulk",
    "Pulses": "bagged grain",
    "Loose": "break bulk",
    "General Pallets": "break bulk",
    "20FT CONTAINER": "containers",
    "40 FT Container": "containers",
    "Drums": "break bulk",
    "50KG Bags": "bagged grain",
    "LOOSE": "break bulk",
    "Any common cargo": "break bulk",
    "40 FT Container/Any common cargo": "containers",
    "40FT Container": "containers",
    "Teff": "bagged grain",
    "Lentils": "bagged grain",
    "White Wheat": "bagged grain",
    "White Wheat ": "bagged grain",
    "Mixed Teff": "bagged grain",
    "White Maize": "bagged grain",
    "White Maize ": "bagged grain",
    "Maize": "bagged grain",
    "Cereals": "bagged grain",
    "20 FT Container": "containers",
    "Fertilizer": "break bulk",
    "Processed Tea Leaves": "break bulk",
    "Wheat": "bagged grain",
    "Forklift": "break bulk",
    "Cement": "break bulk",
    "Malting Barley": "bagged grain",
    "Beans": "bagged grain",
    "Soap and Oil": "break bulk",
    "Cooking Oil": "break bulk",
    "Soap": "break bulk",
    "Crude Oil": "break bulk",
    "Green Grams": "bagged grain",
    "Dry food stuff": "bagged grain",
    "Stationaries": "break bulk",
    "Assorted Items": "break bulk",
    "Sulphuric Acid": "break bulk",
    "Food": "bagged grain",
    "Grains,": "bagged grain",
    "Grains": "bagged grain",
    "Cereals, Vegetable oil": "bagged grain",
    "Electric Poles": "break bulk",
    "Hides": "break bulk",
    "Natural Gums": "break bulk",
    "Diesel": "break bulk",
    "Metal -Wind turbines": "break bulk",
    "Cables": "break bulk",
    "Dry Food Staff- Cereals": "bagged grain",
    "Veterinery Items": "break bulk",
    " Construction Explosives": "break bulk",
    "Shoes": "break bulk",
    "Phamaciticals": "break bulk",
    "Agro products - Seeds": "bagged grain",
    "Fertilizer & Cereals": "bagged grain",
    "Telecommunications Items": "break bulk",
    "Unimix (porridge flour)": "bagged grain",
    "Petroleum,  white oils": "break bulk",
    "Petroleum products": "break bulk",
    "Clinker and finished cement": "break bulk",
    "clinker and finished cement": "break bulk",
    "Bitumen": "break bulk",
    "Books": "break bulk",
    "Medical supplies": "break bulk",
    "Cereals ": "bagged grain",
    "Barley": "bagged grain",
    "Seeds": "break bulk",
    "BEER": "break bulk",
    "Sorghum": "bagged grain",
    "CSB+": "break bulk",
    "Oil": "break bulk",
    "Rilico": "break bulk",
    "Rice": "bagged grain",
    "Assorted": "break bulk",
    "Wheat/Maize": "bagged grain",
    "Pipes": "break bulk",
    "Spaghetti": "break bulk",
    "CONTAINER": "containers",
    "FERTILIZER": "break bulk",
    "Sorgham": "bagged grain",
    "CSB": "break bulk",
    "Pestcides /acarisides": "break bulk",
    "Chemicals -rawmaterials": "break bulk",
    "food products": "break bulk",
    "Fuel Oil": "break bulk",
    "Salt": "break bulk",
    "Clinker Gypsum": "break bulk",
    "Mix commodity cereals and veg oil": "break bulk",
    "Maize and Wheat Flour": "bagged grain",
    "Vegetable Oil": "break bulk",
    "Sugar": "break bulk",
}

road_surface_map = {
    "very_poor": 1,
    "poor": 2,
    "bad": 3,
    "fair": 4,
    "good": 5,
    "excellent": 6,
}
