import numpy as np

toilet_facilities_w1 = {
    1: "Flush toilet, private",
    2: "Flush toilet, shared",
    3: "Pit latreen, private ventilated",
    4: "Pit lantreen, shared ventilated",
    5: "Pit lantreen, private not ventilated",
    6: "Pit lantreen, shared not ventilated",
    7: "Bucket",
    8: "Field / forest",
    9: "Others",
}

toilet_facilities_w2 = {
    1: "Flush toilet, private",
    2: "Flush toilet, shared",
    3: "Pit latreen, private ventilated",
    4: "Pit lantreen, shared ventilated",
    5: "Pit lantreen, private not ventilated",
    6: "Pit lantreen, shared not ventilated",
    7: "Bucket",
    8: "Field / forest",
    9: "Other(Specify)",
}

toilet_facilities_w2_w3_ss = {
    1: "Pit latrine private",
    2: "Shared pit latrine",
    3: "Private flush toilet",
    4: "Shared flush toilet",
    5: "Bucket toilet",
    6: "Uses the bush",
    7: "Flying toilet",
    -98: "Don't know",
    -99: "Refused to respond",
}


toilet_facilities_w3 = {
    1: "Flush toilet",
    2: "Pit latrine, ventilated VIP",
    3: "Pit latrine, with slab",
    4: "PIT LATRINE, WITHOUT SLAB",
    5: "COMPOSTING TOILET",
    6: "Bucket",
    7: "Field /forest",
    8: "Others",
}

toilet_facilities_w4_ss = {
    1: "Flush/pour flush to: piped sewer system",
    2: "Flush/pour flush to:septic tank",
    3: "Flush/pour flush to: pit latrine",
    4: "Flush/pour flush to: elsewhere",
    5: "Flush/pour flush to: unknown place/not sure/DK where",
    6: "Ventilated improved pit latrine (VIP)",
    7: "Pit latrine with slab",
    8: "Pit latrine without slab/open pit",
    9: "Composting toilet",
    10: "Bucket",
    11: "Hanging toilet/hanging latrine",
    12: "No facilities or bush or field",
    1000: "Other (specify)",
    -98: "Don'tknow",
    -99: "Refused to respond",
}

toilet_facilities_uganda_2009 = {
    1: "Covered pit latrine private",
    2: "Covered pit latrine shared",
    3: "Vip latrine private",
    4: "Vip latrine shared",
    5: "Uncovered pit latrine",
    6: "Flush toilet private",
    7: "Flush toilet shared",
    8: "Bush",
    9: "Other",
}

toilet_facilities_uganda_2010_2011 = {
    1: "Covered pit latrine private",
    2: "Covered pit latrine shared",
    3: "VIP latrine private",
    4: "VIP latrine shared",
    5: "Uncovered pit latrine",
    6: "Flush toilet private",
    7: "Flush toilet shared",
    8: "Bush",
    9: "Other (specify)",
}

toilet_facilities_uganda_2013_2015 = {
    10: "Flush Toilet",
    11: "VIP Latrine",
    12: "Covered Pit latrine with slab",
    13: "Covered Pit latrine without slab",
    14: "Uncovered Pit latrine with slab",
    15: "Uncovered Pit latrine without slab",
    16: "Ecosan (compost toilet)",
    17: "No facility/Bush/Polythene bags/Bucket",
    96: "Other (specify)",
}

toilet_facilities_uganda_2018_2019 = {
    11: "Flush To Piped Sewer System",
    12: "Flush To Septic Tank",
    13: "Flush To Pit Latrine",
    14: "Flush To Open Drain",
    18: "Flush To DK Where",
    21: "Ventilated Improved Pit Latrine",
    22: "Pit Latrine With Slab",
    23: "Pit Latrine Without Slab/Open Pit",
    31: "Composting Toilet",
    41: "Bucket (>> 23)",
    51: "Hanging Toilet/Hanging Latrine",
    95: "No Facility/Bush/Field/Polythene (>> 23)",
    96: "Other (Specify)",
}

toilet_facilities_shared = {
    1: "shared",
    2: "private",
}

sanitation_classification = {
    "1. FLUSH TO PIPED SEWER SYSTEM": "At least basic",
    "10. TWIN PIT WITHOUT SLAB": "Unimproved",
    "11. OTHER COMPOSTING TOILET": "At least basic",
    "12. Bucket": "Unimproved",
    "13. CONTAINER BASED SANITATION": "At least basic",
    "14. HANGING TOILET/LATRINE": "Unimproved",
    "15. NO FACILITY/Field/forest": "Open defecation",
    "2. FLUSH TO SEPTICTANK": "At least basic",
    "3. Flush TO PIT LATRINE": "At least basic",
    "4. FLUSH TO OPEN DRAIN": "Unimproved",
    "5. FLUSH TO DO NOT KNOW WHERE": "Unimproved",
    "6. Pit latrine with slab": "At least basic",
    "7. PIT LATRINE WITHOUT SLAB": "Unimproved",
    "8. OPEN PIT": "Unimproved",
    "9. TWIN PIT WITH SLAB": "At least basic",
    "Bucket": "Unimproved",
    "COMPOSTING TOILET": "At least basic",
    "Field / forest": "Open defecation",
    "Field /forest": "Open defecation",
    "Flush toilet": "At least basic",
    "Flush toilet, private": "At least basic",
    "Flush toilet, shared": "Limited service",
    "PIT LATRINE, WITHOUT SLAB": "Unimproved",
    "Pit lantreen, private not ventilated": "Unimproved",
    "Pit lantreen, shared not ventilated": "Unimproved",
    "Pit lantreen, shared ventilated": "Limited service",
    "Pit latreen, private ventilated": "At least basic",
    "Pit latrine, ventilated VIP": "At least basic",
    "Pit latrine, with slab": "At least basic",
    "Neighbor's toilet": "Limited service",
    "Communal latrine": "Limited service",
    "Other family's toilet": "Limited service",
    "not able to walk to a toilet": "Open defecation",
    "plastic sack/bag": "Open defecation",
    "My child's home toilet": "Limited service",
    "Not functional": "Open defecation",
    "Communal latrine build by OXFAM": "Limited service",
    "Doesn't have waste/swere disposal": "Unimproved",
    "Dag out covred with canvas": "Open defecation",
    # Wave 1, 2, and 3 south Sudan
    "Bucket toilet": "Unimproved",
    "Don't know": np.nan,
    "Flying toilet": "Open defecation",
    "Pit latrine private": "Unimproved",
    "Private flush toilet": "At least basic",
    "Refused to respond": np.nan,
    "Shared flush toilet": "Limited service",
    "Shared pit latrine": "Limited service",
    "Uses the bush": "Open defecation",
    # Wave 4 south sudan
    "Composting toilet": "At least basic",
    "Don'tknow": np.nan,
    "Flush/pour flush to: elsewhere": "At least basic",
    "Flush/pour flush to: piped sewer system": "At least basic",
    "Flush/pour flush to: pit latrine": "At least basic",
    "Flush/pour flush to: unknown place/not sure/DK where": "Unimproved",
    "Flush/pour flush to:septic tank": "At least basic",
    "Hanging toilet/hanging latrine": "Unimproved",
    "No facilities or bush or field": "Open defecation",
    "Other (specify)": "Other (specify)",
    "Pit latrine with slab": "At least basic",
    "Pit latrine without slab/open pit": "Unimproved",
    "Ventilated improved pit latrine (VIP)": "At least basic",
    # Others wave 4 South Sudan
    "Bush ": "Open defecation",
    "Going to the neighbours  latrine. ": "Limited service",
    "Somewhere else or bush ": "Open defecation",
    "Somewhere or Busch ": "Open defecation",
    "bush ": "Open defecation",
    "bushes ": "Open defecation",
    "nearby bush elsewhere ": "Open defecation",
    "no facilities available in the household. ": "Open defecation",
    "no facilities available. ": "Open defecation",
    "no facility available in the household. ": "Open defecation",
    "no latrine facility available in the household. ": "Limited service",
    "somewhere or Busch ": "Open defecation",
    "the share with other people ": "Limited service",
    "there is no latrine facility at all here. ": "Limited service",
    "there is no latrine facility available in the house. ": "Limited service",
    "there is no latrine facility available in the household. ": "Limited service",
    "there is no latrine facility available. ": "Limited service",
    "use neighbour's toilet. ": "Limited service",
    "Busch": "Open defecation",
    "Bush": "Open defecation",
    "Bush  or elsewhere": "Open defecation",
    "Near by bush": "Open defecation",
    "Nearby Bush": "Open defecation",
    "Nearby bush or sharing with neighborhood": "Open defecation",
    "Somewhere or Busch": "Open defecation",
    "any nearby bush": "Open defecation",
    "any where else": "Open defecation",
    "anywhere within Vicinity": "Open defecation",
    "bush": "Open defecation",
    "goes to bush": "Open defecation",
    "nearby Bush or any hidden ground": "Open defecation",
    "no facilities available in the household.": "Limited service",
    "no toilet": "Open defecation",
    "share with neigber": "Limited service",
    "somewhere or Busch": "Open defecation",
    "they do not have toilet in the house but they are sharing with neighbours": "Limited service",
    "well constructed toilet": "At least basic",
    # Djibouti 2012
    "Hole in the ground with rudimentary fence": "Unimproved",
    "Improved latrines": "At least basic",
    "In nature": "Open defecation",
    "Simple latrine": "Unimproved",
    "WC with flush": "At least basic",
    # Djibouti 2017
    "Latrine simple": "Unimproved",
    "WC without flush": "At least basic",
    # Uganda
    # 2009-2011
    "Covered pit latrine private": "Unimproved",
    "Covered pit latrine shared": "Unimproved",
    "Vip latrine private": "At least basic",
    "VIP latrine private": "At least basic",
    "Vip latrine shared": "Limited service",
    "VIP latrine shared": "Limited service",
    "Uncovered pit latrine": "Unimproved",
    "Flush toilet private": "At least basic",
    # Guesing
    "Flush toilet shared": "Limited service",
    "Bush": "Open defecation",
    "Other": "Other (specify)",
    "Flush Toilet": "At least basic",
    # 2013
    "Covered Pit latrine without slab, private": "Unimproved",
    # Guessing
    "Covered Pit latrine with slab, shared": "At least basic",
    "Covered Pit latrine with slab, private": "At least basic",
    "Covered Pit latrine without slab, shared": "Unimproved",
    "VIP Latrine, shared": "Limited service",
    "Flush Toilet, shared": "Limited service",
    "Flush Toilet, private": "At least basic",
    "VIP Latrine, private": "At least basic",
    "Other (specify), shared": "Other (specify)",
    "Uncovered Pit latrine with slab, private": "At least basic",
    "Uncovered Pit latrine without slab, shared": "Unimproved",
    "Uncovered Pit latrine without slab, private": "Unimproved",
    "Uncovered Pit latrine with slab, shared": "Limited service",
    "Ecosan (compost toilet), private": "At least basic",
    "Other (specify), private": "Other (specify)",
    # 2018
    "Pit Latrine Without Slab/Open Pit, private": "Unimproved",
    "Pit Latrine With Slab, private": "At least basic",
    # Guessing
    "Pit Latrine With Slab, shared": "At least basic",
    "Pit Latrine Without Slab/Open Pit, shared": "Unimproved",
    "Ventilated Improved Pit Latrine, private": "At least basic",
    "Flush To Piped Sewer System, private": "At least basic",
    "Ventilated Improved Pit Latrine, shared": "Limited service",
    "Flush To Septic Tank, private": "At least basic",
    # Should shared by unimproved?
    "Flush To Septic Tank, shared": "At least basic",
    "Flush To Pit Latrine, shared": "At least basic",
    "Flush To DK Where, shared": "Unimproved",
    "Hanging Toilet/Hanging Latrine, shared": "Unimproved",
    "Flush To Open Drain, private": "Unimproved",
    "Hanging Toilet/Hanging Latrine, private": "Unimproved",
    "Composting Toilet, private": "At least basic",
    "Flush To Pit Latrine, private": "At least basic",
    "Other (Specify), private": "Other (specify)",
    "Flush To DK Where, private": "Unimproved",
    "Other (Specify), shared": "Other (specify)",
    "Flush To Piped Sewer System, shared": "At least basic"
    # 2018
}

source_drinking_water_rainy_season_w1 = {
    1: "Tap inside the house",
    2: "Private tap in the compound",
    3: "Shared tap in compound",
    4: "Communal tap outside compound",
    5: "Water from kiosk/retailer",
    6: "Protected well / spring, private",
    7: "Protected well / spring, shared",
    8: "Unprotected well / spring",
    9: "River / lake / pound",
    10: "Rain water",
    11: "Other (Specify)",
}

source_drinking_water_w2_w3_ss = {
    1: "Water filtering stations with common network /stand pipe (koshk)",
    2: "Mechanical boreholes with common network/standpipe (koshk)",
    3: "Deep boreholes (donkey) with or without network",
    4: "Hand pumps",
    5: "Sand filters with common network stand pipe (koshk)",
    6: "Shallow wells (dug wells)",
    7: "Hafeer/Dam without filter (still open water)",
    8: "Hafeer/Dam with filter (still open water)",
    9: "Running open water source (river, pond, tura’a)",
    10: "Water vendor (tanker-cart-bearer) from deep boreholes",
    11: "Water vendor – from shallow wells pond/river/spring",
    -98: "Don't know",
    -99: "Refused to respond",
}

source_drinking_water_w4_ss = {
    1: "Piped water into dwelling",
    2: "Piped water to yard/plot",
    3: "Public tap/standpipe",
    4: "Tubewell/borehole",
    5: "Protected dug well",
    6: "Unprotected dug well",
    7: "Protected spring",
    8: "Unprotected spring",
    9: "Rainwater collection",
    10: "Bottled water",
    11: "Cart with small tank/drum",
    12: "Tanker-truck",
    13: "Surface water (river, dam, lake,pond,stream,canal,irrigation channels)",
    1000: "Other (specify)",
    -98: "Don'tknow",
    -99: "Refused to respond",
}

source_drinking_water_rainy_season_w3 = {
    1: "PIPED WATER INTO DWELLING",
    2: "PIPED WATER INTO YARD/PLOT",
    3: "PIPED WATER PUBLIC TAP/STANDPIPE",
    4: "TUBEWELL/BOREHOLE",
    5: "PROTECTED DUG WELL",
    6: "UNPROTECTED DUGWELL",
    7: "PROTECTED SPRING",
    8: "UNPROTECTED SPRING",
    9: "RAINWATER COLLECTION",
    10: "PIPED WATER KIOSK/RETAILER",
    11: "BOTTLED WATER",
    12: "CART WITH SMALL TANK/DRUM",
    13: "TANKER-TRUCK",
    14: "SURFACE WATER",
    15: "OTHER,SPECIFY.",
}

time_water_source_dry_w3 = {
    1: "below 15 minutes",
    2: "16-30 minutes",
    3: "31-45 minutes",
    4: "46-60 minutes",
    5: "61-90 minutes",
    6: "91-120 minutes",
    7: "above 120 minutes",
}

region_code_w1 = {
    1: "Tigray",
    2: "Afar",
    3: "Amhara",
    4: "Oromia",
    5: "Somalie",
    6: "Benshagul Gumuz",
    7: "SNNP",
    12: "Gambelia",
    13: "Harari",
    14: "Addis Ababa",
    15: "Diredwa",
}

region_code_w3 = {
    1: "Tigray",
    2: "Afar",
    3: "Amhara",
    4: "Oromia",
    5: "Somalie",
    6: "Benshagul Gumuz",
    7: "SNNP",
    12: "Gambelia",
    13: "Harari",
    14: "Addis Ababa",
    15: "Diredwa",
}

region_code_w4 = {
    "1. TIGRAY": "Tigray",
    "6. BENISHANGUL GUMUZ": "Benshagul Gumuz",
    "15. DIRE DAWA": "Diredwa",
    "7. SNNP": "SNNP",
    "13. HARAR": "Harari",
    "12. GAMBELA": "Gambelia",
    "2. AFAR": "Afar",
    "14. ADDIS ABABA": "Addis Ababa",
    "4. OROMIA": "Oromia",
    "5. SOMALI": "Somalie",
    "3. AMHARA": "Amhara",
}

region_code_uganda = {1: "Central", 2: "Eastern", 3: "Northern", 4: "Western"}

wave_1_label = {
    "hh_s9q10": toilet_facilities_w1,
    "hh_s9q13": source_drinking_water_rainy_season_w1,
    "saq01": region_code_w1,
}

wave_3_label = {
    "hh_s9q10": toilet_facilities_w3,
    "hh_s9q13": source_drinking_water_rainy_season_w3,
    "saq01": region_code_w3,
}

wave_4_label = {"saq01": region_code_w4}

source_drinking_water_uganda_2009 = {
    1: "Private connection to pipeline (tap) >>9",
    2: "Public taps",
    3: "Bore-hole",
    4: "Protected well/spring",
    5: "Unprotected well/spring",
    6: "River, stream, lake, pond",
    7: "Vendor/tanker truck",
    8: "Gravity flow scheme",
    9: "Rain water",
    96: "Other (specify)",
}

source_drinking_water_uganda_2010_2011 = {
    1: "Private connection to pipeline (Tap)",
    2: "Public taps",
    3: "Bore-hole",
    4: "Protected well/spring",
    5: "Unprotected well/spring",
    6: "River, stream, lake, pond",
    7: "Vendor/Tanker truck",
    8: "Gravity flow scheme",
    9: "Rain water",
    96: "Other (specify)",
}

source_drinking_water_uganda_2013_2015 = {
    10: "Piped water into the dwelling",
    11: "Piped water to the yard",
    12: "Public tap",
    13: "Borehole in yard/plot",
    14: "Public borehole",
    15: "Protected well/spring",
    16: "Unprotected well/spring",
    17: "River/ Stream/ Lake",
    18: "Vendor",
    19: "Tanker truck",
    20: "Gravity flow scheme",
    21: "Rain water",
    22: "Bottled water",
    96: "Other (specify)",
}

source_drinking_water_uganda_2018_2019 = {
    10: "Piped water into dwelling",
    11: "Piped water to the yard",
    12: "Public taps",
    13: "Borehole in yard / plot",
    14: "Public borehole",
    15: "Protected well / spring",
    16: "Unprotected well / spring",
    17: "River / stream / lake",
    18: "Vendor",
    19: "Tanker truck",
    20: "Gravity flow schemes",
    21: "Rain water",
    22: "Bottled water",
    96: "Other (specify)",
}

drinking_water_classification = {
    "1. PIPED WATER INTO DWELLING": "At least basic",
    "10. RAINWATER COLLECTION": "At least basic",
    "11. PIPED WATER KIOSK/RETAILER": "At least basic",
    "12. BOTTLED WATER": "Limited service",
    "13. CART WITH SMALL TANK/DRUM": "At least basic",
    "14. SACHET WATER": "Limited service",
    "15. TANKER-TRUCK": "At least basic",
    "16. SURFACE WATER": "Surface water",
    "2. PIPED WATER INTO YARD/PLOT": "At least basic",
    "3. PIPED WATER TO NEIGHBOUR": "At least basic",
    "4. PIPED WATER PUBLIC TAP/STANDPIPE": "At least basic",
    "5. TUBEWELL/BOREHOLE": "At least basic",
    "6. PROTECTED DUG WELL": "At least basic",
    "7. UNPROTECTED DUGWELL": "Unimproved",
    "8. PROTECTED SPRING": "At least basic",
    "9. UNPROTECTED SPRING": "Unimproved",
    "BOTTLED WATER": "Limited service",
    "CART WITH SMALL TANK/DRUM": "At least basic",
    "Communal tap outside compound": "At least basic",
    "PIPED WATER INTO DWELLING": "At least basic",
    "PIPED WATER INTO YARD/PLOT": "At least basic",
    "PIPED WATER KIOSK/RETAILER": "At least basic",
    "PIPED WATER PUBLIC TAP/STANDPIPE": "At least basic",
    "PROTECTED DUG WELL": "At least basic",
    "PROTECTED SPRING": "At least basic",
    "Private tap in the compound": "At least basic",
    "Protected well / spring, private": "At least basic",
    "Protected well / spring, shared": "At least basic",
    "RAINWATER COLLECTION": "At least basic",
    "River / lake / pound": "Surface water",
    "SURFACE WATER": "Surface water",
    "Shared tap in compound": "At least basic",
    "TANKER-TRUCK": "At least basic",
    "TUBEWELL/BOREHOLE": "At least basic",
    "Tap inside the house": "At least basic",
    "UNPROTECTED DUGWELL": "Unimproved",
    "UNPROTECTED SPRING": "Unimproved",
    "Unprotected well / spring": "Unimproved",
    "Water from kiosk/retailer": "At least basic",
    "Rain water": "At least basic",
    # Wave 1, 2 and 3 South Sudan
    "Deep boreholes (donkey) with or without network": "At least basic",
    "Hafeer/Dam with filter (still open water)": "Surface water",
    "Hafeer/Dam without filter (still open water)": "Surface water",
    "Hand pumps": "At least basic",
    "Mechanical boreholes with common network/standpipe (koshk)": "At least basic",
    "Running open water source (river, pond, tura’a)": "Surface water",
    "Sand filters with common network stand pipe (koshk)": "At least basic",
    "Shallow wells (dug wells)": "Unimproved",
    "Water filtering stations with common network /stand pipe (koshk)": "At least basic",
    "Water vendor (tanker-cart-bearer) from deep boreholes": "At least basic",
    "Water vendor – from shallow wells pond/river/spring": "Surface water",
    "Don't know": np.nan,
    ".z": np.nan,
    "Refused to respond": np.nan,
    # Wave 4 South Sudan
    "Bottled water": "Limited service",
    "Cart with small tank/drum": "At least basic",
    "Don'tknow": np.nan,
    "Other (specify)": "Other (specify)",
    "Piped water into dwelling": "At least basic",
    "Piped water to yard/plot": "At least basic",
    "Protected dug well": "At least basic",
    "Protected spring": "At least basic",
    "Public tap/standpipe": "At least basic",
    "Rainwater collection": "At least basic",
    "Surface water (river, dam, lake,pond,stream,canal,irrigation channels)": "Surface water",
    "Tanker-truck": "At least basic",
    "Tubewell/borehole": "At least basic",
    "Unprotected dug well": "Unimproved",
    "Unprotected spring": "Unimproved",
    # Others wave 4 South Sudan
    '"Borehole. "': "At least basic",
    '"Hand pump "': "At least basic",
    '"Hand pump. "': "At least basic",
    '"Handpuomp "': "At least basic",
    '"Surface  water  treatment  facility. "': "At least basic",
    '"borehole "': "At least basic",
    '"bushes "': "Unimproved",
    '"direct  from  river "': "Unimproved",
    '"hand pump "': "At least basic",
    '"hand pump. "': "At least basic",
    '"handpuomp "': "At least basic",
    '"inside fence "': "At least basic",
    '"running  water from the stream. "': "Unimproved",
    '"water bring by donkey "': "At least basic",
    '"water is to be brought by the prisoners "': "At least basic",
    '"we are buying from boys selling using donkey "': "At least basic",
    '"we buying from boys selling water using donkey "': "At least basic",
    "Handpuomp": "At least basic",
    "bore hole": "At least basic",
    "borehole hole": "At least basic",
    "donkey water": "At least basic",
    "hand pump.": "At least basic",
    "water sell by donkey man": "At least basic",
    "we are buying from boys selling using donkey": "At least basic",
    # Djbouti 2017
    "Borehole (well with pump)": "At least basic",
    "Direct connection from a borehole": "At least basic",
    "ONEAD external connection, by pipe": "At least basic",
    "Other": "Other",
    "Public fountain": "At least basic",
    "River / stream / rainwater / water reservoir / underground cistern": "Surface water",
    "Running water (ONEAD internal connection)": "At least basic",
    "Tanker": "At least basic",
    "Traditional wells": "Unimproved",
    "Wells fitted out without a pump": "At least basic",
    # Djibouti 2012
    "Drilling (then with pump)": "At least basic",
    "ONED external connection, by pipe": "At least basic",
    "River / stream / rainwater": "Surface water",
    "Running water (internal ONED connection)": "At least basic",
    "Tanker truck (Seller)": "At least basic",
    "Traditional well": "Unimproved",
    "Well without pump": "At least basic",
    # Uganda 2013-2015, 2018-2019, 2009-2011
    "River/ Stream/ Lake": "Surface water",
    "River / stream / lake": "Surface water",
    "River, stream, lake, pond": "Surface water",
    "Unprotected well/spring": "Unimproved",
    "Unprotected well / spring": "Unimproved",
    "Public borehole": "At least basic",
    "Piped water to the yard": "At least basic",
    "Private connection to pipeline (Tap)": "At least basic",
    "Public tap": "At least basic",
    "Public taps": "At least basic",
    "Protected well/spring": "At least basic",
    "Protected well / spring": "At least basic",
    "Piped water into the dwelling": "At least basic",
    "Piped water into dwelling": "At least basic",
    # Guessing
    "Vendor": "Surface water",
    # Assuming the gravity flow is protected
    "Gravity flow scheme": "At least basic",
    "Gravity flow schemes": "At least basic",
    "Rain water": "At least basic",
    "Borehole in yard/plot": "At least basic",
    "Borehole in yard / plot": "At least basic",
    "Bore-hole": "At least basic",
    "Bottled water": "Limited service",
    "Tanker truck": "At least basic",
    "Vendor/Tanker truck": "At least basic",
}

ethiopia_month_name_map = {
    "Tikimt": 2,
    "Yekatit": 6,
    "Miaziya": 8,
    "Sene": 10,
    "Tahsas": 4,
    "Ginbot": 9,
    "Meskerem": 1,
    "Tir": 5,
    "Nehassie": 12,
    "Hamle": 11,
    "Megabit": 7,
}


DHS_toilet_facility_map = {
    "bucket toilet": "Unimproved",
    "composting toilet": "At least basic",
    "flush to piped sewer system": "At least basic",
    "flush to pit latrine": "At least basic",
    "flush to septic tank": "At least basic",
    "flush to somewhere else": "At least basic",
    "flush, don't know where": "At least basic",
    "hanging toilet/latrine": "Unimproved",
    "no facility/bush/field": "Open defecation",
    "other": "Other",
    "pit latrine with slab": "At least basic",
    "pit latrine without slab/open pit": "Unimproved",
    "ventilated improved pit latrine (vip)": "At least basic",
}


french_t_english = {
    "q05_21": {
        "Eau courante (branchement intérieur ONEAD)": "Running water (ONEAD internal connection)",
        "Branchement extérieur ONEAD, par tuyau": "ONEAD external connection, by pipe",
        "Puits traditionnels": "Traditional wells",
        "Fontaine publique": "Public fountain",
        "Forage (puits avec pompe)": "Borehole (well with pump)",
        "Rivière/cours d'eau/eau de pluie/retenue d'eau/citerne enterrée": "River / stream / rainwater / water reservoir / underground cistern",
        "Branchement direct à partir d'un forage": "Direct connection from a borehole",
        "Puits aménagés sans pompe": "Wells fitted out without a pump",
        "Camion-citerne": "Tanker",
        "Autre": "Other",
    },
    "q05_21_autre": {
        "AU VOISIN": "TO NEIGHBOR",
        "AUCUN": "NO",
        "AVEC LE LOYER": "WITH THE RENT",
        "BRANCHEMENT MOSQUEE": "MOSQUE CONNECTION",
        "CITERNE": "TANK",
        "DESSALEMENT": "DESALINATION",
        "EAU GRATUIT DU VOISI": "FREE WATER OF THE VOISI",
        "GRATUIT PAR LE VOISI": "FREE BY VOISI",
        "PAR VOISIN": "BY NEIGHBOR",
        "PORTER DES JERRICAN": "CARRY JERRICANS",
        "RAMEME DAUTRE QUATIE": "RAMEME OF OTHER QUATIE",
        "RÉCUPÉRER AUX VOISIN": "RECOVER FROM NEIGHBORS",
        "VOISIN": "NEIGHBOUR",
        "VOISIN GRATUIT": "FREE NEIGHBOR",
        "VOISINAGE": "NEIGHBORHOOD",
    },
    "q05_28": {
        "Dans la nature": "In nature",
        "Latrine simple": "Latrine simple",
        "Trou dans le sol avec clôture rudimentaire": "Hole in the ground with rudimentary fence",
        "WC avec chasse d'eau": "WC with flush",
        "WC sans chasse d'eau": "WC without flush",
    },
    "q05_29": {"Partagé": "Sharing", "Privé": "Private"},
    "region": {
        "Ali-Sabieh": "Ali Sabeh",
        "Dikhil": "Dilkhil",
        "Djibouti ville": "Djibouti",
        "Obock": "Obock",
        "Tadjourah": "Tadjourah",
        "Arta": "Arta",
    },
}

water_label_dji = {
    1: "Running water (internal ONED connection)",
    2: "ONED external connection, by pipe",
    3: "Public fountain",
    4: "Tanker truck (Seller)",
    5: "Drilling (then with pump)",
    6: "Well without pump",
    7: "Traditional well",
    8: "River / stream / rainwater",
    9: "Other",
}

toilet_label_dji = {
    1: "WC with flush",
    2: "Improved latrines",
    3: "Simple latrine",
    4: "Hole in the ground with rudimentary fence",
    5: "In nature",
}

toilet_sharing_dji = {
    1: "Private",
    2: "Sharing",
}

region_label_dji = {
    1: "Djibouti",
    2: "Ali Sabeh",
    3: "Dilkhil",
    4: "Tadjourah",
    5: "Obock",
    6: "Arta",
}

dji_2012_label = {
    "CL09": water_label_dji,
    "CL14": toilet_label_dji,
    "CL15": toilet_sharing_dji,
    "IM01": region_label_dji,
}

ghs_smod_map = {
    11.0: 1,
    12.0: 1,
    13.0: 1,
    21.0: 2,
    22.0: 3,
    23.0: 3,
    30.0: 3,
    10.0: 0,
    -200.0: np.nan,
}


uganda_labels = {
    "H9q07": [
        source_drinking_water_uganda_2009,
        source_drinking_water_uganda_2010_2011,
        source_drinking_water_uganda_2013_2015,
        source_drinking_water_uganda_2018_2019,
    ],
    "H9q22": [
        toilet_facilities_uganda_2009,
        toilet_facilities_uganda_2010_2011,
        toilet_facilities_uganda_2013_2015,
        toilet_facilities_uganda_2018_2019,
    ],
}

DHS_water_source_map = {
    "bottled water": "At least basic",
    "cart with small tank": "Unimproved",
    "other": "Other",
    "piped into dwelling": "At least basic",
    "piped to yard/plot": "At least basic",
    "protected spring": "At least basic",
    "protected well": "At least basic",
    "public tap/standpipe": "At least basic",
    "rainwater": "At least basic",
    "river/dam/lake/ponds/stream/canal/irrigation channel": "Surface water",
    "tanker truck": "Unimproved",
    "tube well or borehole": "At least basic",
    "unprotected spring": "Unimproved",
    "unprotected well": "Unimproved",
    "public to neighborhood": "At least basic",
}
