commodity_group_map = {
    # PULSES & VEGGIES
    "Beans": "Pulses and vegetables",
    "Beans (dry)": "Pulses and vegetables",
    "beans": "Pulses and vegetables",
    "Cassava Flour": "Pulses and vegetables",
    "Cassava flour": "Pulses and vegetables",
    "Groundnuts": "Pulses and vegetables",
    "ground nuts": "Pulses and vegetables",
    "Okra": "Pulses and vegetables",
    "vegetables": "Pulses and vegetables",
    "Plantains": "Pulses and vegetables",
    "Kale": "Pulses and vegetables",
    "Onions (red)": "Pulses and vegetables",
    "Tomatoes": "Pulses and vegetables",
    "Cabbage": "Pulses and vegetables",
    "Potatoes (Irish)": "Pulses and vegetables",
    # FRUIT
    "fruits": "Fruit",
    "Bananas": "Fruit",
    # BREADS & CEREALS
    "maize": "Bread and Cereals",
    "Maize": "Bread and Cereals",
    "Maize (white)": "Bread and Cereals",
    "Maize flour": "Bread and Cereals",
    "Maize Flour": "Bread and Cereals",
    "Rice": "Bread and Cereals",
    "rice": "Bread and Cereals",
    "Sorghum": "Bread and Cereals",
    "Sorghum (food aid)": "Bread and Cereals",
    "Sorghum (white)": "Bread and Cereals",
    "Wheat": "Bread and Cereals",
    "wheat": "Bread and Cereals",
    "Wheat flour": "Bread and Cereals",
    "millet": "Bread and Cereals",
    "Millet": "Bread and Cereals",
    "teff": "Bread and Cereals",
    "Bread": "Bread and Cereals",
    # MEAT
    "Meat": "Meat",
    "Meat (camel)": "Meat",
    "Meat (beef)": "Meat",
    "Meat (goat)": "Meat",
    "beef": "Meat",
    "Beef": "Meat",
    # MILK, CHEESE, & EGGS
    "milk": "Milk, cheese and eggs",
    "Milk": "Milk, cheese and eggs",
    "Milk (UHT)": "Milk, cheese and eggs",
    "Milk (cow, pasteurized)": "Milk, cheese and eggs",
    "Milk (camel, fresh)": "Milk, cheese and eggs",
    "Milk (cow, fresh)": "Milk, cheese and eggs",
    # OILS AND FATS
    "Veg Oil": "Oils and fats",
    "Oil (vegetable)": "Oils and fats",
    "Cooking fat": "Oils and fats",
    # SUGAR
    "sugar": "Sugar, jam, honey, chocolate and candy",
    "Sugar": "Sugar, jam, honey, chocolate and candy",
    # CONDIMENTS
    "Salt": "Condiments",
}

adj_countries_name_map = {
    "CAR": "Central African Republic",
    "DRC": "Democratic Republic of the Congo",
    "Ethiopia": "Ethiopia",
    "kenya": "Kenya",
    "Sudan": "Sudan",
    "Uganda": "Uganda",
}

eth_admin_conversion = {
    # "AA ZONE1": "??",
    "AFDER": "Afder",
    # "ALABA SW": "??",
    # "AMARO SW": "??",
    "ARSI": "Arsi",
    "ASOSA": "Assosa",
    "BALE": "Bale",
    "BORENA": "Borena",
    "C. TIGRAY": "Central Tigary",
    "DIRE DAWA": "Dire Dawa",
    "E. GOJAM": "East Gojjam",
    "E. HARERGE": "East Hararge",
    "E. SHEWA": "East Shewa",
    "E. TIGRAY": "East Tigray",
    "E. WELLEGA": "East Wellega",
    "GAMO GOFA": "Gamo Gofa",
    "GEDEO": "Gedoe",
    "GODE": "Gode",
    # "GODERE": "??",
    "GUJI": "Guji",
    "GURAGE": "Gurage",
    "HADIYA": "Hadiya",
    "HARAR/HUNDENE": "Harer",
    "JIJIGA": "Jijiga",
    "JIMMA": "Jimma",
    "KAMASHI": "Kamashi",
    # "KONSO SW": "??",
    "KORAHE": "Korahe",
    "LIBEN": "Liben",
    "MEKELE": "Mekele Especial Zone",
    "METEKEL": "Metekel",
    "N. GONDER": "North Gondar",
    "N. SHEWA (R3)": "North Shewa",
    # "N. SHEWA (R4)": "North Shewa",
    "N. WELLO": "North Wollo",
    "NW. TIGRAY": "North Western Tigray",
    "OROMIYA": "Oromiya",
    "S. GONDER": "South Gondor",
    "S. TIGRAY": "South Tigray",
    "S. WELLO": "South WWolo",
    "S.W. SHEWA": "South West Shewa",
    "SELTI": "Siliti",
    "SIDAMA": "Sidama",
    "SOUTH OMO": "South Omo",
    "W. GOJAM": "West Gojjam",
    "W. HAMRA": "Wag Himra",
    "W. HARERGE": "West Harage",
    "W. TIGRAY": "Western Tigray",
    "WELAYITA": "Wolayita",
    "WEST SHEWA": "West Shewa",
    # "ZONE 1": "???",
    # "ZONE 2": "???",
    # "ZONE 3": "???",
    "ZONE1": "Zone 01",
    "ZONE2": "Zone 02",
    "ZONE3": "Zone 03",
    "ZONE4": "Zone 04",
    "ZONE5": "Zone 05",
}

ss_admin_conversion = {
    "juba": "Juba",
    "Bor south": "Bor South",
    "Bor south ": "Bor South",
    "kajo keji": "Kajo-Keji",
    "Kajo keji": "Kajo-Keji",
    "kajo  keji": "Kajo-Keji",
    "lainya": "Lainya",
    "morobo": "Morobo",
    "terekeka": "Terekeka",
    "yei": "Yei",
    "Kapoeta   south": "Kapoeta South",
    "kapoeta south": "Kapoeta South",
    "Kapoeta south": "Kapoeta South",
    "Kapoeta east": "Kapoeta East",
    "Kapoeta north": "Kapoeta North",
    "Twic east": "Twic East",
    "Rumbek centre": "Rumbek Centre",
    "Rumbek north": "Rumbek North",
    "rumbek north": "Rumbek North",
    "Yirol east": "Yirol East",
    "Yirol west": "Yirol West",
    "Aweil centre": "Aweil Centre",
    "Aweil east": "Aweil East",
    "Aweil north": "Aweil North",
    "Aweil west": "Aweil West",
    "Aweil south": "Aweil South",
    "rubkona": "Rubkona",
    "maban": "Maban",
    "maiwut": "Maiwut",
    "maiwut ": "Maiwut",
    "malakal": "Malakal",
    "manyo": "Manyo",
    "melut": "Melut",
    "renk": "Renk",
    "gogrial east": "Gogrial East",
    "gogrial west": "Gogrial West",
    "tonj east": "Tonj East",
    "tonj north": "Tonj North",
    "tonj south": "Tonj South",
    "jur river": "Jur River",
    "Jur river": "Jur River",
    "wau": "Wau",
    "ezo": "Ezo",
    "ibba": "Ibba",
    "maridi": "Maridi",
    "mundri east": "Mundri East",
    "mundri west": "Mundri West",
    "mvolo": "Mvolo",
    "nzara": "Nzara",
    "tambura": "Tambura",
    "yambio": "Yambio",
    "abiemnhom": "Abiemhom",
    "Mundri east": "Mundri East",
    "Mundri west": "Mundri West",
    "Gogrial east": "Gogrial East",
    "Gogrial west": "Gogrial West",
    "Tonj north": "Tonj North",
    "Tonj south": "Tonj South",
    "Tonj east": "Tonj East",
}
